### ISSUE TITLE
Tab bar Dragging Weird rectangle 

### ISSUE THREAD

**Issue by im-izz** [yiiyahui/Neptune-Firefox#1]
Hallo, when I drag It looks like this.
![image](https://github.com/user-attachments/assets/19d7afe2-ecab-46d2-b764-c3df8462460a)
Windows 10 Latest
Firefox 128.0

**Comment by yiiyahui** [comment]
Wow. I never noticed this issue before. It has been fixed. Please update userchrome.css. Thanks for the submission.
