### ISSUE TITLE
Tabs jumping arround when dragging (Animation Problem)

### ISSUE THREAD

**Issue by im-izz** [yiiyahui/Neptune-Firefox#11]
![firefox_ZeVbNXhEi9](https://github.com/user-attachments/assets/afefe419-1983-4a3e-9731-b48eebe767f0)

**Comment by yiiyahui** [comment]
This is ff's original animation; i haven't added anything. perhaps modifying the tab width has affected it.

**Comment by im-izz** [comment]
Can't you change/modify it?

**Comment by faralk** [comment]
Having a similar issue here too... 

Maybe it has to do with the tab transparency but moving tabs is really unsmooth and feels off (even if you didn't change the original Firefox animation).

**Comment by yiiyahui** [comment]
This animation has nothing to do with color; it's just a 200ms transition, following its original animation effect.
```css
:root {
  --animation-easing-function: cubic-bezier(.07, .95, 0, 1);
}
```

you can change its curve, for example, to make it transition at a constant speed.
```css
  --animation-easing-function: cubic-bezier(0.42, 0, 0.58, 1) !important;
```

BTW, there is also a 200ms transition in the current version. I might not drag the tabs often. anyway, I will add it next time.

**Comment by faralk** [comment]
Thanks! I will wait for the update.
