### ISSUE TITLE
Windows bug: icon contrast on dark background, pop up resize missing

### ISSUE THREAD

**Issue by yofriadi** [yiiyahui/Neptune-Firefox#12]
1. on Windows, when opening a website with dark background, like Spotify, only extension icon shows
![1](https://github.com/user-attachments/assets/d3678639-6af6-4764-9d3e-159cb0c76a01)

2. when popping out video, cant resize video size.
3. video timeline not show (also on macOS).

4. and one last thing, if you prefer rounded corner, how I make video pop out use sharp corner instead? because I use sharp corner for window in Windows
![image](https://github.com/user-attachments/assets/1c876b6c-3ca2-4d0e-b75f-4d57270e5182)
![image](https://github.com/user-attachments/assets/c9bd97b7-60cf-4bb3-b48b-8af9c8f85ed4)

**Comment by yiiyahui** [comment]
1：README..

![Screenshot](https://github.com/user-attachments/assets/8f38c4ed-338f-48e5-80cc-367a62ebba88)

2: look for
```css
@-moz-document url("chrome://global/content/pictureinpicture/player.xhtml") {
...
...
}
```

and

```css
 #timestamp,
.end-controls,
.scrubber-no-drag,
.control-item::after,
.scrollbar-topmost,
```
and delete them.

If there are updates, you might need to delete them each time.😁

**Comment by yofriadi** [comment]
oh right, sorry I am using this skin again in my Windows PC and skip the README part.

> If there are updates, you might need to delete them each time.😁
man, it is small things compared to your work, thanks again for creating this 🙌
