### ISSUE TITLE
Text turns white when mouseover in selection fields

### ISSUE THREAD

**Issue by jgassens** [yiiyahui/Neptune-Firefox#14]
I found this little bug

https://github.com/user-attachments/assets/ccda4047-d980-4d3c-bfba-8e3cb82a9708

It turns the text white against a white background, so you can't see it. Would you happen to have an idea why/how to fix it?

PS love the theme, keep up the good work!

**Comment by yiiyahui** [comment]
It has been fixed. You can now update it from the repository.

**Comment by jgassens** [comment]
Perhaps I've missed something... I downloaded the latest commit and put it in my profile, but I see the same issue happening. Not sure why...

**Comment by yiiyahui** [comment]
> Perhaps I've missed something... I downloaded the latest commit and put it in my profile, but I see the same issue happening. Not sure why...

Please tell me the website's address.

**Comment by yiiyahui** [comment]
Sorry, it was my mistake. I didn’t test it on macOS last time, but now it’s fixed. Please download it again.
