### ISSUE TITLE
Text not Accomodating Background

### ISSUE THREAD

**Issue by Vir7ualll** [yiiyahui/Neptune-Firefox#18]
The intended behavior is that the text will adjust to the background and become dark where the background is bright and bright where the background is dark, however the text is bright for me regardless and it messes with visibility. Was wondering if there was a fix for this, especially since on the screenshots for this project you can clearly see text adjust to the background properly.

![Screenshot (6)](https://github.com/user-attachments/assets/3ac204f9-2c72-4bde-bd63-3e5dc9a37b31)

**Comment by yiiyahui** [comment]
The text color does not change with the background image color. for this screenshot, you could add a shadow to the card text, which might help solve your problem.

**Comment by Vir7ualll** [comment]
that does suck, was wondering how you were able to do it for your screenshots though, even the top bar accommodates the background. Either way thanks for the shadow idea!

**Comment by yiiyahui** [comment]
[Adaptive Tab Bar Color](https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-colour/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)

**Comment by Vir7ualll** [comment]
I am using that, even did your settings, still wont do the multicolor tabbar like in the first screenshot you have, but i can live without that. Thanks for letting me know the text not changing color is expected behavior, still sucks but oh well
