### ISSUE TITLE
New FF build breaks top bar

### ISSUE THREAD

**Issue by zakroma** [yiiyahui/Neptune-Firefox#20]
New FF nightly build breaks the top bar (see attached screenshot).
How to fix this?

<img width="1696" alt="SCR-20241004-jwvd" src="https://github.com/user-attachments/assets/da3811df-1bc2-4bcc-bd44-9120139faa68">

**Comment by yiiyahui** [comment]
Not supported in the nightly version, but here are some possible solutions
1：Search `#titlebar #toolbar-menubar’` change to `#toolbar-menubar`
2：Search `#titlebar` change to `.browser-titlebar`

**Comment by zakroma** [comment]
OMG! Can't believe it was so easy to fix!
Thank you for your wonderful theme and such a prompt response!!!!
