### ISSUE TITLE
Goofy behavior on mac full screen

### ISSUE THREAD

**Issue by jerichoi224** [yiiyahui/Neptune-Firefox#21]
FIrst the theme looks amazing. Thanks for the amazing job
Currently using Librewolf (just in case it matters)

When in full screen in Mac, if I put my mouse on the top of the screen, the mac bar comes down, and all the tabs get shifted, getting pushed into the web page view. Is there a way to fix this?

thx

![SCR-20241026-otpe](https://github.com/user-attachments/assets/60ba4190-ce60-4725-a10e-c140f07e80db)

**Comment by yiiyahui** [comment]
install  [Adaptive Tab Bar Color](https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-colour/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) will display the correct colors.

see the README.

**Comment by jerichoi224** [comment]
It works!
I did see the readme, But I read it as necessary only if I wanted the adaptive color bars. 
Guess I thought it would just be white if I didn't install it. Thanks for the help!
