### ISSUE TITLE
Option to reduce padding

### ISSUE THREAD

**Issue by ztomer** [yiiyahui/Neptune-Firefox#22]
Love your theme!

Would it be possible to add an option to reduce the top and bottom paddings?
 
I made a quick hack over your theme with less padding here (*)
https://github.com/ztomer/Neptune-Firefox

And it looks like this (**):
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/bb82193b-38f3-49aa-8114-1d3827c15069">

(*) 20 min with ALOT of claude.ai help. I have no idea what's I'm doing.
(**) I'm aware that everything is not aligned well.

**Comment by yiiyahui** [comment]
If you want to adjust the padding of the toolbar, just modify the padding of the following elements. BTW, I think the top and bottom padding should be the same to ensure that the elements above are centered.

Change `12px` to the value you want.

```js
#nav-bar {
	padding: 12px 0 12px calc(92px - var(--toolbar-start-end-padding) / 2) !important;
}

#TabsToolbar {
	padding: 0 calc(var(--tab-min-height) + 2 * var(--toolbar-start-end-padding)) 12px 0 !important;
}
```
---
This is the position of the traffic light button. adjust its position to match the height of the toolbar and ensure they are vertically centered.

```js
@media (-moz-platform: macos) {

	.titlebar-buttonbox-container {
		top: 18px;
	}
}
```

**Comment by ztomer** [comment]
Changed the value from 12 to 4, works beautifully. Thanks!

<img width="1067" alt="image" src="https://github.com/user-attachments/assets/868563c0-c4a3-453f-a282-0e452742c411">
