### ISSUE TITLE
Firefox nightly breaks address bar

### ISSUE THREAD

**Issue by zakroma** [yiiyahui/Neptune-Firefox#23]
Hello! 

New FF nightly build breaks address bar by stretching it full width (see screenshot).
<img width="1591" alt="SCR-20241028-lxlh" src="https://github.com/user-attachments/assets/80a284e4-7787-4d1c-885d-6852c3496ef5">

I know this is not a theme for a nightly build but maybe you might have a solution for this one.

Thank you!

**Comment by yiiyahui** [comment]
OK, you need to modify two places in userChrome.css.

1: Search `#titlebar` change to `.browser-titlebar`

2: Locate

```css
#urlbar {
	height: var(--urlbar-min-height) !important;
	width: 100% !important;
	left: 0 !important;
	font-size: 12.5px !important;
```
 change to

```css
#urlbar {
	height: var(--urlbar-min-height) !important;
	width: var(--urlbar-width) !important;
	margin: 0 !important;
	font-size: 12.5px !important;
```

**Comment by zakroma** [comment]
Thank you once again!!! My firefox looks perfect again!
