### ISSUE TITLE
Multi row tabs?

### ISSUE THREAD

**Issue by 1000deaths** [yiiyahui/Neptune-Firefox#26]
Would it be possible to add multi row tabs to this theme? Just like on here: https://github.com/Tagggar/Firefox-Alpha?tab=readme-ov-file#multi-row-tabs

I use my second monitor vertically so this would be really useful. If not then it's okay, I just haven't gotten used to vertical tabs

**Comment by yiiyahui** [comment]
If tab wrapping is allowed, the toolbar height will change. whether in a horizontal or vertical tab layout, when many tabs are always open, the best solution should be tab groups, which have already appeared in nightly and may be coming soon.
