### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by F3R96** [yiiyahui/Neptune-Firefox#29]
Hi! I saw that you were able to fix the latest firefox update with themes. Is there any chance you could help me with mine? I don't have a clue on how to fix it. 

I'm using a custom whitesur theme that also has a folder called neptune 

https://drive.google.com/file/d/1ixk8uVdB2UYofcuQgtI7pFCZLWy4UUHC/view?usp=sharing Here's the link to my folder

**Comment by yiiyahui** [comment]
This is a worm virus? Sorry, I didn't unzip it

**Comment by F3R96** [comment]
> This is a worm virus? Sorry, I didn't unzip it

No no, it's my chrome folder

**Comment by F3R96** [comment]
https://www.reddit.com/r/FirefoxCSS/comments/1h1vv1g/133_update_broke_my_theme/ I also made this reddit post.
It has my pastebin codes there

**Comment by yiiyahui** [comment]
I misunderstood you, but I might not be able to help you. I haven't used this theme and don't know what errors it has. I saw someone on reddit reply that there are solutions in the link you provided. you can edit those files based on the content in there or wait for the author to update it.

**Comment by F3R96** [comment]
The only error it has are the close, max and minimize buttons missing since 133. 
I asked for your help because someone from discord told me that you were the one who fixed this theme. 


I'm sorry for bothering you.



Ps: I installed your theme and it looks cool, but for some reason I can seen to be able to move the back and forward arrows when personalizing the looks of it

**Comment by yiiyahui** [comment]
Yes, they are hidden when they are disabled, and this also happens during customization. I keep forgetting to fix this. they should be visible during customization. you can search for `#back-button[disabled]` and `#forward-button[disabled]` and remove them. Fix it next time
