### ISSUE TITLE
Search bar results outline: how to remove it

### ISSUE THREAD

**Issue by zakroma** [yiiyahui/Neptune-Firefox#35]
Hello,

How can I remove the outline in the search results?

<img width="335" alt="SCR-20241219-lmgg" src="https://github.com/user-attachments/assets/e4b99b2a-15dd-4ae1-be14-ddadfe6a8562" />

Thank you!

**Comment by yiiyahui** [comment]
The nightly is full of bugs. Strangely, I don't see the color of this border in the nightly 135.0a1, it's transparent. Try this.
Search:

```css
.urlbarView-results {
	padding: 6px !important;

	> .urlbarView-row {
		border-block: var(--button-border) !important;
```

change to:

```css
	> .urlbarView-row {
		border-block: 1px solid transparent !important;
```

**Comment by zakroma** [comment]
This is it! Thank you once again!!! <3
