### ISSUE TITLE
Glitch when when in full screen on macOS when not using Adaptive Tab Color

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [yiiyahui/Neptune-Firefox#4]
https://github.com/user-attachments/assets/7fde70a2-f936-4e99-b195-d7bcd5a6c0f2

Awesome theme btw <3

**Comment by yiiyahui** [comment]
What happened?

**Comment by yiiyahui** [comment]
This is not a bug, as the toolbar background color is a transparent color—it has always been transparent. this is why it will be filled by the extension. this color scheme cannot work without the extension.

**Comment by IdkWhatToCallMe123** [comment]
Oh oops my bad.
