### ISSUE TITLE
Unified Extension Menu and Hamburger Menu Not Clickable

### ISSUE THREAD

**Issue by bengalbroy** [yiiyahui/Neptune-Firefox#5]
on macOS (128.0.3) the unified extension menu icon and the hamburger menu icon aren't clickable, only the new tab button is clickable.

**Comment by IdkWhatToCallMe123** [comment]
Does it show a highlight when you hover your cursor over?

**Comment by bengalbroy** [comment]
> Does it show a highlight when you hover your cursor over?

Nope, nothing at all.

**Comment by IdkWhatToCallMe123** [comment]
Sound like something is overlapping the other buttons. Maybe try to reset your toolbar layout.

**Comment by bengalbroy** [comment]
> Sound like something is overlapping the other buttons. Maybe try to reset your toolbar layout.

That's one of the first things I tried and it didn't help. The only thing that helps is removing the userChrome altogether

**Comment by IdkWhatToCallMe123** [comment]
Oh uhh
You sure that you don't have any other previous customization still applied in about:config?
Have you made absolute sure that you have followed the installation instructions tip to toe?

Just a bit confusing as it is perfectly working for me on the same version xd

**Comment by bengalbroy** [comment]
> Oh uhh You sure that you don't have any other previous customization still applied in about:config? Have you made absolute sure that you have followed the installation instructions tip to toe?
> 
> Just a bit confusing as it is perfectly working for me on the same version xd

Yeah, I even tried completely reinstalling Firefox from scratch and it still did it :/

**Comment by IdkWhatToCallMe123** [comment]
Do you use another language? In that case try to change the display language in Firefox for English or something I've seen CSS customizations before bug out when using other languages.

**Comment by bengalbroy** [comment]
> Do you use another language? In that case try to change the display language in Firefox for English or something I've seen CSS customizations before bug out when using other languages.

Nah, it's in English. I just tried changing it to another language and then back to English too, and still no dice.

**Comment by IdkWhatToCallMe123** [comment]
oh boy ehh

At this I feel like this is something that you've already tried but have you tried using different versions of the theme?

**Comment by bengalbroy** [comment]
> oh boy ehh
> 
> At this I feel like this is something that you've already tried but have you tried using different versions of the theme?

Yeah, the previous one works, it's just the latest one that doesn't

**Comment by IdkWhatToCallMe123** [comment]
Well uh
I tried double checking my versions and it still works for me at least.
At this point I really don't know what it could be. 
You don't have any other apps open like bettermouse or linear mouse that can mess with input?
![圖片](https://github.com/user-attachments/assets/ac6f8267-df3d-458f-8075-e8cf775fe0f3)

**Comment by IdkWhatToCallMe123** [comment]
Not sure if this matters but can you check if your build number of macOS lines up with mine by running `sw_vers` in the terminal?
![圖片](https://github.com/user-attachments/assets/d6a143b8-31c6-4d6e-b560-8afb568ae53f)

**Comment by bengalbroy** [comment]
> Well uh I tried double checking my versions and it still works for me at least. At this point I really don't know what it could be. You don't have any other apps open like bettermouse or linear mouse that can mess with input? 

I don't. I think for now I'll just stick with the previous version. I thought at first it might be because of the sequoia beta, so I booted into sonoma, but it did it there too. (Literally as I was typing this your message to check the version no came up 😅 )

**Comment by IdkWhatToCallMe123** [comment]
> > Well uh I tried double checking my versions and it still works for me at least. At this point I really don't know what it could be. You don't have any other apps open like bettermouse or linear mouse that can mess with input?
> 
> I don't. I think for now I'll just stick with the previous version. I thought at first it might be because of the sequoia beta, so I booted into sonoma, but it did it there too. (Literally as I was typing this your message to check the version no came up 😅 )

I'm not really the author of project I suppose if it works for you just fine and as long no one else experiences this we can probably just discard this until some one else that knows better than me can take a look at this.

Still really weird that it is happening at all 🙃

**Comment by ChenghaoMou** [comment]
I can confirm this happened to me as well after updating to the latest version. Reverting back to a6bad60b5a80b4a5a5f0eec0820712319a989ee8 solves the issue.

**Comment by ChenghaoMou** [comment]
Based on my test, I found the possible snippet that renders it unresponsive: https://github.com/yiiyahui/Neptune-Firefox/commit/6338882657c3009adb268ace60fcf71ba610c35d?diff=unified&w=0#r144778775

As soon as I add it back, the buttons are working again.

**Comment by IdkWhatToCallMe123** [comment]
Oh okay can confirm that it is happening if you clone the repository rather than downloading the latest version from releases. Now I get it xd

**Comment by yiiyahui** [comment]
The repository's version is sometimes unstable, even though it is more up-to-date. 
It's my fault...... you can add and modify this part to fix it.

Line:1113

```css
:root[tabsintitlebar] #titlebar {
	will-change: unset !important;
}

@media (-moz-platform: macos) {
	#nav-bar,
	#TabsToolbar {
		padding-block: 11px !important;
	}
```
