### ISSUE TITLE
Blur effects for dropdown menus

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [yiiyahui/Neptune-Firefox#6]
Not sure if this fits what you are going for, but if it does it could be cool if you copied some of the blur effects from this theme: [https://www.reddit.com/r/FirefoxCSS/comments/1au0bw0/blurfox/](https://www.reddit.com/r/FirefoxCSS/comments/1au0bw0/blurfox/)

**Comment by yiiyahui** [comment]
Thank you for your suggestion. In the previous version, the blur effect in the settings menu was removed due to wallpaper issues. However, it's now resolved. I will use blur effects in appropriate places, such as some menus or backgrounds, but not everywhere.
