### ISSUE TITLE
Increase Width of Suggested Search Results in Firefox Skin

### ISSUE THREAD

**Issue by itslukebond** [yiiyahui/Neptune-Firefox#7]
I’m really enjoying your skin! My only critique is that the width of the suggested search results is too narrow, causing the text to be cut off prematurely. This limits the visibility of the suggestions, making it difficult to read and select the appropriate one. Is there anything I can change in the CSS to make the suggestions take up the full width of the box, allowing more of the text to be displayed? 

![Screenshot 2024-08-04 at 15 08 03](https://github.com/user-attachments/assets/10142167-7146-4bbb-ba04-18c50aafa8ac)

**Comment by yiiyahui** [comment]
Because if we don't limit their width, the search results will wrap into two lines. This is a choice we made to ensure it always displays in a single line.

**Comment by yofriadi** [comment]
hi, is it possible limit width with percentage based value?
because I have this much width and have problem as author explain here, thank you anyway for the skin.
![Screenshot 2024-08-11 at 11 19 55](https://github.com/user-attachments/assets/234a3961-70a3-4db6-89bd-0dc745610261)

**Comment by yiiyahui** [comment]
It's already based on percentage width. you can look at lines 279 and 284 to adjust it.

**Comment by yofriadi** [comment]
hi @yiiyahui just want to confirm, the latest release note say
> The display range of urlbar search results has been completely adjusted, and it now shows fully.

what does this means ya?
since you completed this issue, I believe it is related to issue in here, but mine is still shows as before the update, or perhaps this is not tested on macOS

here is some picture
![Screenshot 2024-08-14 at 15 52 19](https://github.com/user-attachments/assets/9f8e3db0-009f-4918-ba25-d20bd52d36b4)

thank you in advance

**Comment by yiiyahui** [comment]
isn't an error, it can display fully only when the search results don't include url, such as search suggestions....just like in the first image of this issue.

**Comment by yofriadi** [comment]
ah I got it, turns it is me that misunderstood the wording, thank you for the response.
